#' Interactive cis-QTL browser
#'
#' Launches a Shiny application for exploring cis-QTL associations.
#' Users can select genes, view associated SNPs, and visualize the genotype
#' effect on phenotypes using [plotGenotypeEffect()].
#'
#' @param tqe A [tQTLExperiment] with genotype data.
#' @param cis_gr A [GenomicRanges::GRanges] object containing cis-QTL results
#'   (e.g., from [readTQTL()]).
#' @param gene_col Name of the metadata column in `cis_gr` containing gene
#'   symbols. Default: `"gene_symbol"`.
#' @param snp_col Name of the metadata column in `cis_gr` containing SNP IDs.
#'   Default: `"variant_id"`.
#' @param phenotype_col Name of the metadata column in `cis_gr` containing
#'   phenotype/gene IDs. Default: `"phenotype_id"`.
#' @param pval_col Name of the metadata column in `cis_gr` containing p-values.
#'   Default: `"pval_nominal"`.
#' @param pval_thresh Optional numeric threshold for filtering associations by
#'   p-value. If `NULL` (default), all associations are included.
#'
#' @return A Shiny application object (invisibly). Call this function in an
#'   interactive R session to launch the browser.
#'
#' @details
#' The browser provides two tabs:
#' - **Genotype effect**: Beeswarm plot of phenotype values by SNP genotype,
#'   generated by [plotGenotypeEffect()].
#' - **cis associations**: Filterable data table of all associations for the
#'   selected gene.
#'
#' Navigation is via dropdown menus: select a gene symbol (searchable), then
#' a cis-SNP for that gene, then click "Plot" to visualize.
#'
#' @import shiny
#' @importFrom bslib bs_theme
#' @importFrom DT dataTableOutput renderDataTable datatable
#' @export
#'
#' @examples
#' \dontrun{
#' # Build example tQTLExperiment
#' exdir <- system.file("extdata", package = "tQTLExperiment")
#' tqe <- tQTLExperiment(
#'     plinkPrefix = file.path(exdir, "chr22-n100"),
#'     phenoFile   = file.path(exdir, "mean-pheno-n100.bed"),
#'     genome      = "hg38"
#' )
#'
#' # Load demo results
#' demodir <- system.file("demodir", package = "tQTLExperiment")
#' res <- readTQTL(demodir, mode = "cis_nominal")
#'
#' # Launch browser
#' app <- run_cis_qtl_browser(tqe, res$pairs, pval_thresh = 0.05)
#' }
run_cis_qtl_browser <- function(tqe, cis_gr,
                                gene_col      = "gene_symbol",
                                snp_col       = "variant_id",
                                phenotype_col = "phenotype_id",
                                pval_col      = "pval_nominal",
                                pval_thresh   = NULL) {

  cis_df <- as.data.frame(S4Vectors::mcols(cis_gr))

  # optional nominal p-value filter
  if (!is.null(pval_thresh) && pval_col %in% names(cis_df)) {
    cis_df <- cis_df[!is.na(cis_df[[pval_col]]) &
                       cis_df[[pval_col]] <= pval_thresh, , drop = FALSE]
    message("After p-value filter (", pval_thresh, "): ", nrow(cis_df), " rows")
  }

  all_symbols <- sort(unique(cis_df[[gene_col]][!is.na(cis_df[[gene_col]])]))

  get_cis_snps <- function(gene) {
    rows <- !is.na(cis_df[[gene_col]]) & cis_df[[gene_col]] == gene
    unique(cis_df[[snp_col]][rows])
  }

  get_cis_table <- function(gene) {
    rows <- !is.na(cis_df[[gene_col]]) & cis_df[[gene_col]] == gene
    cis_df[rows, , drop = FALSE]
  }

  # ── UI ──────────────────────────────────────────────────────────────────
  ui <- fluidPage(
    theme = bs_theme(bootswatch = "flatly"),
    titlePanel("cis-QTL Browser"),

    sidebarLayout(
      sidebarPanel(
        width = 3,
        selectizeInput(
          "gene",
          "Gene symbol",
          choices  = all_symbols,
          selected = all_symbols[1],
          options  = list(placeholder = "Type to search…")
        ),
        selectInput(
          "snp",
          "cis-SNP",
          choices = NULL
        ),
        actionButton("go", "Plot", class = "btn-primary mt-2 w-100")
      ),

      mainPanel(
        width = 9,
        tabsetPanel(
          tabPanel(
            "Genotype effect",
            br(),
            plotOutput("geno_plot", height = "500px")
          ),
          tabPanel(
            "cis associations",
            br(),
            dataTableOutput("cis_table")
          )
        )
      )
    )
  )

  # ── server ───────────────────────────────────────────────────────────────
  server <- function(input, output, session) {

    observeEvent(input$gene, {
      req(input$gene)
      snps <- get_cis_snps(input$gene)
      updateSelectInput(session, "snp",
        choices  = snps,
        selected = snps[1]
      )
    }, ignoreNULL = TRUE)

    cis_data <- reactive({
      req(input$gene)
      get_cis_table(input$gene)
    })

    plot_params <- eventReactive(input$go, {
      list(gene = input$gene, snp = input$snp)
    }, ignoreNULL = FALSE)

    output$geno_plot <- renderPlot({
      p <- plot_params()
      req(p$gene, p$snp)

      pid <- cis_df[[phenotype_col]][
        !is.na(cis_df[[gene_col]]) &
        cis_df[[gene_col]] == p$gene &
        cis_df[[snp_col]]  == p$snp
      ][1]

      req(!is.na(pid))

      plotGenotypeEffect(
        tqe,
        snp_id       = p$snp,
        phenotype_id = pid
      )
    })

    output$cis_table <- renderDataTable({
      datatable(
        cis_data(),
        selection = "none",
        rownames  = FALSE,
        filter    = "top",
        options   = list(
          pageLength = 25,
          scrollX    = TRUE
        )
      )
    })
  }

  shinyApp(ui, server)
}
