#' Interactive cis-QTL browser
#'
#' Launches a Shiny application for exploring cis-QTL associations.
#' Users can select genes, view associated SNPs, and visualize the genotype
#' effect on phenotypes using [plotGenotypeEffect()].
#'
#' @param tqe A [tQTLExperiment] with genotype data.
#' @param cis_gr A [GenomicRanges::GRanges] object containing cis-QTL results
#'   (e.g., from [readTQTL()]).
#' @param gene_col Name of the metadata column in `cis_gr` containing gene
#'   symbols. Default: `"gene_symbol"`.
#' @param snp_col Name of the metadata column in `cis_gr` containing SNP IDs.
#'   Default: `"variant_id"`.
#' @param phenotype_col Name of the metadata column in `cis_gr` containing
#'   phenotype/gene IDs. Default: `"phenotype_id"`.
#' @param pval_col Name of the metadata column in `cis_gr` containing p-values.
#'   Default: `"pval_nominal"`.
#' @param pval_thresh Optional numeric threshold for filtering associations by
#'   p-value. If `NULL` (default), all associations are included.
#'
#' @return A Shiny application object (invisibly). Call this function in an
#'   interactive R session to launch the browser.
#'
#' @details
#' The browser provides two tabs:
#' - **Genotype effect**: Beeswarm plot of phenotype values by SNP genotype,
#'   generated by [plotGenotypeEffect()].
#' - **cis associations**: Filterable data table of all associations for the
#'   selected gene.
#'
#' Navigation is via dropdown menus: select a gene symbol (searchable), then
#' a cis-SNP for that gene, then click "Plot" to visualize.
#'
#' @import shiny
#' @importFrom bslib bs_theme
#' @importFrom DT dataTableOutput renderDataTable datatable
#' @export
#'
#' @examples
#' if (interactive()) {
#'   # Load MAGE chr17 genotypes and pre-computed tensorQTL results
#'   plink_paths <- cache_mage_chr17_plink(verbose = FALSE)
#'   plpre <- tools::file_path_sans_ext(plink_paths[["bed"]])
#'   data(mageSEfilt, package="CSHLvc2026")
#'   cd <- as.data.frame(colData(mageSEfilt))
#'   mm <- model.matrix(~ factor(batch) + population + sex, data = cd)
#'   mm <- mm[, -1, drop = FALSE]   # remove (Intercept)
#'   tqe <- tQTLExperimentFromRSE(
#'    se              = mageSEfilt,
#'    plinkPrefix     = plpre,
#'    covariateMatrix = mm,
#'    genome          = "hg38"
#'    )
#'   tqe <- addGeneSymbols(tqe)
#'   demd = cache_demo_data()
#'   res <- readTQTL(dirname(demd$parquet), mode = "cis_nominal", x = tqe)
#'   newpairs = res$pairs
#'   newpairs = annotateTensorQTLResults(newpairs)
#'
#'   # Launch browser with p-value filter
#'   run_cis_qtl_browser(tqe, newpairs, pval_thresh = 0.05)
#' }
run_cis_qtl_browser <- function(tqe, cis_gr,
                                gene_col      = "gene_symbol",
                                snp_col       = "variant_id",
                                phenotype_col = "phenotype_id",
                                pval_col      = "pval_nominal",
                                pval_thresh   = NULL) {

  cis_df <- as.data.frame(S4Vectors::mcols(cis_gr)) |> dplyr::arrange(pval_nominal) # persistent

  # optional nominal p-value filter
  if (!is.null(pval_thresh) && pval_col %in% names(cis_df)) {
    cis_df <- cis_df[!is.na(cis_df[[pval_col]]) &
                       cis_df[[pval_col]] <= pval_thresh, , drop = FALSE]
    message("After p-value filter (", pval_thresh, "): ", nrow(cis_df), " rows")
  }

  all_symbols <- sort(unique(cis_df[[gene_col]][!is.na(cis_df[[gene_col]])]))

  get_cis_snps <- function(gene) {
    rows <- !is.na(cis_df[[gene_col]]) & cis_df[[gene_col]] == gene
    unique(cis_df[[snp_col]][rows])
  }

  get_cis_table <- function(gene) {
    rows <- !is.na(cis_df[[gene_col]]) & cis_df[[gene_col]] == gene
    cis_df[rows, , drop = FALSE] |> dplyr::arrange(pval_nominal)
  }

  # ── UI ──────────────────────────────────────────────────────────────────
  ui <- fluidPage(
    theme = bs_theme(bootswatch = "flatly"),
    titlePanel("cis-QTL Browser"),

    sidebarLayout(
      sidebarPanel(
        width = 3,
        selectizeInput(
          "gene",
          "Gene symbol",
          choices  = all_symbols,
          selected = all_symbols[1],
          options  = list(placeholder = "Type to search…")
        ),
        selectInput(
          "snp",
          "cis-SNP",
          choices = NULL
        ),
        actionButton("go", "Plot", class = "btn-primary mt-2 w-100")
      ),

      mainPanel(
        width = 9,
        tabsetPanel(
          tabPanel(
            "Genotype effect",
            br(),
            plotOutput("geno_plot", height = "500px")
          ),
          tabPanel(
            "Regression model",
            br(),
            verbatimTextOutput("reg_summary")
          ),
          tabPanel(
            "cis associations",
            br(),
            dataTableOutput("cis_table")
          )
        )
      )
    )
  )

  # ── server ───────────────────────────────────────────────────────────────
  server <- function(input, output, session) {

    observeEvent(input$gene, {
      req(input$gene)
      snps <- get_cis_snps(input$gene)
      updateSelectInput(session, "snp",
        choices  = snps,
        selected = snps[1]
      )
    }, ignoreNULL = TRUE)

    cis_data <- reactive({
      req(input$gene)
      get_cis_table(input$gene)
    })

    plot_params <- eventReactive(input$go, {
      list(gene = input$gene, snp = input$snp)
    }, ignoreNULL = FALSE)

    output$geno_plot <- renderPlot({
      p <- plot_params()
      req(p$gene, p$snp)

      pid <- cis_df[[phenotype_col]][
        !is.na(cis_df[[gene_col]]) &
        cis_df[[gene_col]] == p$gene &
        cis_df[[snp_col]]  == p$snp
      ][1]

      req(!is.na(pid))

      plotGenotypeEffect(
        tqe,
        snp_id       = p$snp,
        phenotype_id = pid
      )
    })

    output$reg_summary <- renderPrint({
      p <- plot_params()
      req(p$gene, p$snp)

      pid <- cis_df[[phenotype_col]][
        !is.na(cis_df[[gene_col]]) &
        cis_df[[gene_col]] == p$gene &
        cis_df[[snp_col]]  == p$snp
      ][1]

      req(!is.na(pid))

      # Get assay index for phenotype
      row_gr <- SummarizedExperiment::rowRanges(tqe, use.names = TRUE)
      pheno_idx <- which(names(row_gr) == pid)

      # Get variant index for SNP
      var_gr <- tqtlVariantRanges(tqe)
      var_idx <- which(S4Vectors::mcols(var_gr)[["snp_id"]] == p$snp)

      # Extract phenotype, genotype, and covariates
      assay_name <- SummarizedExperiment::assayNames(tqe)[1L]
      pheno <- as.numeric(SummarizedExperiment::assay(tqe, assay_name)[pheno_idx, ])
      geno <- as.integer(tqtlGeno(tqe)[, var_idx])

      cov_cols <- setdiff(colnames(SummarizedExperiment::colData(tqe)), "fam_index")
      cov_data <- as.data.frame(SummarizedExperiment::colData(tqe))[, cov_cols,
                                                                     drop = FALSE]

      # Build regression data frame
      reg_data <- data.frame(
        phenotype = pheno,
        genotype  = geno,
        cov_data,
        stringsAsFactors = FALSE
      )

      # Fit linear model
      mod <- lm(phenotype ~ ., data = reg_data)

      # Print summary
      summary(mod)
    })

    output$cis_table <- renderDataTable({
      datatable(
        cis_data(),
        selection = "none",
        rownames  = FALSE,
        filter    = "top",
        options   = list(
          pageLength = 25,
          scrollX    = TRUE
        )
      )
    })
  }

  shinyApp(ui, server)
}
